FROM ubuntu

# build this: e.g docker build -t broker -f Dockerfile.brokercloud .
# to run this container, do:
# docker run -d --name broker -p 1883:1883 --network bridge broker

RUN apk update && apk add mosquitto

EXPOSE 1883
